### PR TITLE
Conflict with DBAL 2.11.0

### PR DESCRIPTION
**Pull request by zonky2**
Conflict with DBAL 2.11.0
see https://github.com/contao/contao/issues/2359

### CODE REVIEW

**Comment by m-vo** [comment]
What's the problem with `doctrine/dbal` 2.11.0?

**Comment by discordier** [comment]
> What's the problem with doctrine/dbal 2.11.0?

https://github.com/doctrine/dbal/issues/4282 - Which is a breaking change as the Query Builder before ignored empty query parts.

The behavior to ignore empty query parts has been restored and will get released as patched version.

Therefore potentially anyone using the Query builder is affected (unless explicitly checking for and ignoring empty strings).

tbh, I did not know that empty query parts are ignored but I suspect there are some extensions out there that will stop working using that version of doctrine.

**Comment by zonky2** [comment]
@baumannsven pls add your bugs with console migration and DBAL...

**Comment by leofeyer** [comment]
Please rebase the PR onto the correct branch.

**Comment by discordier** [comment]
> Please rebase the PR onto the correct branch.

I wonder what branch this might be, considering this repo has only `master` and the PR is against `master`?

**Comment by leofeyer** [comment]
Sorry, my bad. I didn't realize this is not `contao/contao`. 🙈

**Comment by leofeyer** [comment]
So how does this affect Contao? Where exactly does the issue occur?

**Comment by discordier** [comment]
@baumannsven has more information, as he experienced the issue in the migrations, however he seems rather busy lately and might not be able to answer more closely. I'll try to reach out to him.

**Comment by discordier** [comment]
This will need to be updated, as the resolution was not complete and we found another regression, see doctrine/dbal#4330.

So the comflicting versions will be: 2.11.0 & 2.11.1.

Still waiting to hear from @baumannsven though. :disappointed:

**Comment by leofeyer** [comment]
Stale

**Pull request closed without merging**
