### PR TITLE
Revert conflict for ocramius/proxy-manager

### PR DESCRIPTION
**Pull request by ausi**
See https://github.com/contao/conflicts/pull/26#issuecomment-857523349

### CODE REVIEW

**Review by m-vo — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Comment by bytehead** [comment]
Thank you @ausi!

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by ausi** [comment]
I missed that Contao 4.11.4 was not released yet, so Contao 4.11 still has the problem with the proxy manager it seems: https://github.com/contao/contao/issues/3070

**Comment by ausi** [comment]
Not sure how to fix this.

Is there a way to conflict with `ocramius/proxy-manager 2.12.0` while keeping compatibility with `friendsofphp/proxy-manager-lts`?

**Comment by leofeyer** [comment]
I will simply release Contao 4.11.4 now. 😄

**Comment by fritzmg** [comment]
> Is there a way to conflict with `ocramius/proxy-manager 2.12.0` while keeping compatibility with `friendsofphp/proxy-manager-lts`?

What kind of compatibility issues are there? Adding a conflict for `"ocramius/proxy-manager": "2.12.0"` seems fine in Contao 4.11.3, at least in my local instance.

**Comment by ausi** [comment]
> What kind of compatibility issues are there?

See https://github.com/contao/conflicts/pull/26#issuecomment-856893323

**Comment by fritzmg** [comment]
> See [#26 (comment)](https://github.com/contao/conflicts/pull/26#issuecomment-856893323)

Mhm, so that's the whole `replaces` version constraint dicussion all over again.

**Comment by ausi** [comment]
Yes, probably better to replace exact versions instead of whole version ranges.

**Pull request merged**
