### PR TITLE
We are currently not compatible with twig 2.7

### PR DESCRIPTION
**Pull request by Toflar**
See https://github.com/nelmio/NelmioSecurityBundle/issues/197

### CODE REVIEW

**Comment by stof** [comment]
This should be reverted, as only 1.38.0 and 2.7.0 were buggy in Twig. This also prevents installing 2.7.1 which is fixed

**Comment by Toflar** [comment]
No it's correct. We manage conflicts of the whole Managed Edition here. We need to wait until `nelmio/security-bundle` is compatible :)

**Comment by Toflar** [comment]
I see, we can now safely update to 2.7.1. @stof our idea here is to prevent errors for our users. We manage conflicts for them which is why we keep the constraints open until we know things are really fixed 😄

**Comment by Toflar** [comment]
https://github.com/contao/conflicts/pull/3 here we go, thanks for pinging :)

**Comment by stof** [comment]
nelmio/security-bundle is compatible with Twig 2.7.1, as the bug is fixed in it.

**Comment by Toflar** [comment]
Jup, I saw that. Thx for the info :)

**Pull request merged**
