### PR TITLE
Update fail by Ocramius/proxy-manager in 2.12.0

### PR DESCRIPTION
**Pull request by Ainschy**
see https://github.com/Ocramius/ProxyManager/issues/702 it's a problem when composer < 2.0.14

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Comment by leofeyer** [comment]
The fix has been added to the `2.13.0` milestone, so it seems that all `2.12.*` versions will be affected?

**Comment by Seldaek** [comment]
I'd recommend anyone needing this to use friendsofphp/proxy-manager-lts instead, which works with all Composer versions and has broader php compatibility too.

**Comment by m-vo** [comment]
@bytehead + me noticed that this change now unfortunately breaks updates on PHP8 installations:

The problems look like this:
```
  Problem 1
    - Root composer.json requires doctrine/doctrine-migrations-bundle ^2.1 -> satisfiable by doctrine/doctrine-migrations-bundle[2.1.0, ..., 2.2.2].
    - Conclusion: don't install contao/conflicts 9999999-dev (conflict analysis result)
    - Root composer.json requires contao/conflicts @dev -> satisfiable by contao/conflicts[dev-main].

```

`doctrine/migrations` requires `friendsofphp/proxy-manager-lts` which itself replaces `ocramius/proxy-manager: ^2.1`

Not sure how conflicts and replaces work together. 
/cc @Toflar @ausi

**Comment by Seldaek** [comment]
Replace conflicts with conflicts, so yes that's a problem :)

**Comment by ausi** [comment]
Since Contao 4.9.15 is already released (without the proxy-manager requirement) I think we can safely remove this conflict.

**Comment by fritzmg** [comment]
The problem is, that `friendsofphp/proxy-manager-lts` defines that any of its versions replaces any version of `ocramius/proxy-manager` equal or higher than `2.1.0`, which includes `2.12.0`. Imho using `replace` that broadly is not a good practice.

**Pull request merged**
